### ISSUE TITLE
SK6AB omnäms inte på hemsidan

### ISSUE THREAD

**Issue by SA6JKK** [ETAChalmers/ETA-Hemsida#20]
Sökningar på SK6AB länkar till vår hemsida men vi nämner inte namnet på vår radioklubb. Helst en kort notis på Home om att ETA = SK6AB

**Comment by almbr** [comment]
Kan vi lägga till det i About-texten?

**Comment by SA6JKK** [comment]
OK, jag nöjer väl mig med en snutt under about.

**Comment by svirvel** [comment]
Vi hade ju även kunnat lägga till det i texten om eta som finns i footern

**Comment by SA6JKK** [comment]
Förslag på ängring i footer

ETA is an electronics and ham radio community (SK6AB) at Chalmers University of Technology.
